version: '3'
services:
    tigergraph:
        container_name: prv-tigergraph
        image: "docker.tigergraph.com/tigergraph-dev:latest"
        ports:
            - "127.0.0.1:14022:22"
            - "127.0.0.1:9000:9000"
            - "127.0.0.1:14240:14240"
        volumes:
            - prv-tigergraph:/var/lib/tigergraph/data
        ulimits:
            nofile:
                soft: "1000000"
                hard: "1000000"
volumes:
    prv-tigergraph:

