version: "3.3"

services:
    angular:
        container_name: providentia-ng
        build: ./providentia-ng
        environment:
            TZ: "Africa/Johannesburg"
        expose:
            - "4200"
        ports:
            - "4200:4200"
    flask:
        container_name: providentia-flask
        build: ./providentia-flask
        environment:
            TZ: "Africa/Johannesburg"
        expose:
            - "5000"
        ports:
            - "5000:5000"
